CREATE TABLE PRODUCT
(
    "ID" NUMBER(12,0) NOT NULL,
    "NAME" VARCHAR2(40 CHAR),
    "FORENAME" VARCHAR2(40 CHAR)NOT NULL
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("ID");

CREATE SEQUENCE SEQ_PRODUCT MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 CACHE 100;